### ISSUE TITLE
OnChange Event on single element doesn't work

### ISSUE THREAD

**Issue by piero80** [hamzahamidi/ajsf#37]
**Describe the bug**
which template:

* [ ] Bootstrap4FrameworkModule — Bootstrap 4
  
When I try to add an onChange Event in my single field, it doesn't fire. In the previous version of angular-schema-form, this event is triggered. 
Could you help me, please?
This is my layout and my schema
```
 yourFormLayout = [
  "id",
  "name",
  {
    key: "fields",
    items: [
      {
      key:"fields[].name",
      },
      {
        key:"fields[].type",
        type:"select",
        fieldHtmlClass:"field-type",
        onChange: function(modelValue,form) {
         console.log("Test",modelValue);
        }
      },
      {
        key:"fields[].enumerator",
        htmlClass: "enumerator-panel",
        items:{type:"string"}
      }
    ],
  }
]
```
```
  categorySchema = {     
   "type": "object",
   "title": "The Root Schema",
   "required": [
     "id",
     "name",
     "fields"
   ],
   "properties": {
     "id": {
       "type": "string",
       "title": "The Id Schema"
     },
     "name": {
       "type": "string",
       "title": "The Name Schema"
     },
     "fields": {       
       "type": "array",
       "title": "Fields",
       "items": {         
         "type": "object",
         "title": "Items",
         "required": [
           "name",
           "type"
         ],
         "properties": {
           "name": {             
             "type": "string",
             "title": "The Name Schema"             
           },
           "type": {             
             "type": "string",
             "title": "The Type Schema",
             "enum":["String","Integer","Boolean","Enum"]
           },
           "enumerator":{
             "type":"array",
             "title": "Add Enumerator",
             "items":{
                 "type":"string"
             }
           },
           "required":{"type":"boolean"}
           
         }
       }
     }
   }
 }
```
Thanks

**Comment by dbuddha** [comment]
Same issue here.
Is there a workaround?

**Comment by anasofiapaixao** [comment]
I managed to get a workaround working using the form's `(onChanges)` event callback. `onChanges` is very trigger happy (upon initializing a form with data I counted it being invoked 35 times) and for some reason is sometimes called with an empty JSON, but when the event object is not empty and aside from being called in spite of no changes, it is very reliable in the sense that it does catch every change. This workaround as is _does not work_ with `onChange` inside an array, since lodash's `get()` understands `aField[1].value` but does not understand what `aField[].value` means. Since I don't need it, I didn't go through the trouble. This could actually be implemented without lodash's `_.get()` as long as your json is shallow.

I import lodash's `get`:
```
import get from 'lodash/get.js';
```

`onChanges` does not give me the object before the change, so I am keeping track of that myself:
```
  lastChange: any = {};
```

I am recursively traversing the `form` JSON looking for onChange callbacks, and saving them in a map structured like `{ formItemKey: callback }`:
```

  onChanges: any = {};

  populateForm: Function = (entity: any) => {
      this.entity = entity;
      this.lastChange = entity;

      if (this.form) {
        // recursively traverse the form json
        let traverse = item => {
          if (item.items) {
            item.items.map(traverse);
          } else if (item.tabs) {
            item.tabs.map(traverse);
          }

          // keep track of onChange callbacks
          if(item.onChange) {
            this.onChanges[item.key] = item.onChange;
          }
        };
        this.form.map(traverse);
      }
  };

  ngOnInit() {
   ...
    this.populateForm(this.entity);
  }
```

Then in my `onFormChange()` callback I find opportunities for early exit, checking if:
* the JSON is not empty (this happens half the time!) 
* if the fields we have `onChange` callbacks for have actually been changed (no changes happens almost the other half the time)

Then, because all my `onChange` callback return promises, I am using Promise.all [so I can perform a redraw](https://github.com/hamzahamidi/Angular6-json-schema-form/issues/96) after everything is done, because my `onChange`s are updating a select's `titleMap`:
```

  onFormChange(entity: any) {
    let onChanges = [];
    // asf's (onChanges) is very trigger happy and often is invoked with a fake empty
    // object, so ignore it
    if(Object.keys(entity).length === 0 && entity.constructor === Object) {
      return;
    }

    for (let [key, onChange] of Object.entries(this.onChanges)){
      if(get(entity, key) === get(this.lastChange, key)) {
        // no changes, no need to invoke onChange
        continue;
      }

      // check needed so typescript won't complain when compiling
      if(typeof onChange === 'function') {
        onChanges.push(onChange(get(entity, key)));
      }
    }

    if(onChanges.length <= 0) {
      return;
    }

    Promise.all(onChanges)
        .then(() => 
            // redraw
            this.entityForm.initializeForm()
        )
        .catch(error => {
          ...
        });

    this.lastChange = entity;
  }
```

If you do not need promises, or do not need to perform anything after all `onChange`s are resolved (such as a redraw), you could very well just omit creating an array at all.

Finally, link the callback in the html:

```
	<json-schema-form
          ...
	  (onChanges)="onFormChange($event)">
	</json-schema-form>
```

While far from ideal, especially in terms of performance, it does work.

**Comment by dbuddha** [comment]
Nice workarround @anasofiapaixao,

Boa continuação / Keep it going :)

**Comment by lapastina** [comment]
Hi @anasofiapaixao,

Would it be possible for you to publish a complete example on the site "stackblitz.com"?

Thank you very much in advance.

**Comment by samudiogo** [comment]
Thanks @anasofiapaixao ! your approach was the best fit on my solution!
and @lapastina follow below my example based at @anasofiapaixao code:

[https://stackblitz.com/edit/angular-json-schema-form-dynamic-select-data-form-demo](https://stackblitz.com/edit/angular-json-schema-form-dynamic-select-data-form-demo)
